/**
 * AI savings strategy panel for bucket list items.
 *
 * Displays an AI-generated savings strategy using the structured StrategyView
 * component (for JSON strategies) or falls back to markdown (for legacy text).
 * The strategy is generated by the backend using the user's financial context
 * and the specific bucket list item details.
 *
 * Features:
 * - Renders structured JSON strategies with milestone progress, saving tips, etc.
 * - Falls back to markdown rendering for legacy plain-text strategies
 * - Shows when the strategy was generated (relative time like "2h ago")
 * - Provides a regenerate button to request a fresh strategy
 * - Shows loading skeleton while strategy is being generated
 * - Returns null if no strategy exists and none is being generated
 *
 * @module components/bucket-list/strategy-panel
 */
"use client"

import { IconRefresh, IconBulb } from "@tabler/icons-react"
import { Button } from "@/components/ui/button"
import { Skeleton } from "@/components/ui/skeleton"
import { StrategyView } from "@/components/bucket-list/strategy-view"

/**
 * Props for the StrategyPanel component.
 *
 * @property strategy - The AI-generated strategy (JSON string or legacy markdown)
 * @property generatedAt - ISO 8601 timestamp of when the strategy was generated
 * @property onRegenerate - Callback to trigger regeneration of the strategy
 * @property isGenerating - Whether a strategy generation request is in progress
 * @property savedAmount - Current saved amount for computing milestone completion
 * @property targetAmount - Target amount for the bucket list item
 */
interface StrategyPanelProps {
  strategy?: string
  generatedAt?: string
  onRegenerate: () => void
  isGenerating?: boolean
  savedAmount?: number
  targetAmount?: number
}

/**
 * Converts an ISO date string to a human-readable relative time string.
 *
 * @param dateStr - ISO 8601 date string to convert
 * @returns Relative time string like "just now", "5m ago", "2h ago", or "3d ago"
 */
function timeAgo(dateStr: string): string {
  const diff = Date.now() - new Date(dateStr).getTime()
  const mins = Math.floor(diff / 60000)
  if (mins < 1) return "just now"
  if (mins < 60) return `${mins}m ago`
  const hours = Math.floor(mins / 60)
  if (hours < 24) return `${hours}h ago`
  const days = Math.floor(hours / 24)
  return `${days}d ago`
}

/**
 * Renders the AI savings strategy panel within a bucket list item card.
 *
 * Shows either the generated strategy as structured components (or markdown
 * fallback), a loading skeleton while generating, or nothing if no strategy
 * data is available.
 * Includes a header with an amber lightbulb icon and regeneration controls.
 *
 * @param props - Component props (see StrategyPanelProps)
 * @returns The strategy panel JSX or null if no strategy and not generating
 */
export function StrategyPanel({
  strategy,
  generatedAt,
  onRegenerate,
  isGenerating,
  savedAmount = 0,
  targetAmount = 0,
}: StrategyPanelProps) {
  if (!strategy && !isGenerating) return null

  return (
    <div className="mt-3 space-y-2 border-t pt-3">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-1.5">
          <IconBulb className="size-3.5 text-amber-500" />
          <p className="text-xs font-medium text-muted-foreground">
            AI Strategy
          </p>
        </div>
        <div className="flex items-center gap-2">
          {generatedAt && (
            <span className="text-[11px] text-muted-foreground/60">
              {timeAgo(generatedAt)}
            </span>
          )}
          <Button
            variant="ghost"
            size="icon-xs"
            onClick={onRegenerate}
            disabled={isGenerating}
          >
            <IconRefresh
              className={`size-3 ${isGenerating ? "animate-spin" : ""}`}
            />
          </Button>
        </div>
      </div>

      {isGenerating ? (
        <div className="space-y-2">
          <Skeleton className="h-3 w-full" />
          <Skeleton className="h-3 w-4/5" />
          <Skeleton className="h-3 w-3/5" />
          <Skeleton className="h-16 w-full rounded-lg" />
          <Skeleton className="h-3 w-2/3" />
        </div>
      ) : strategy ? (
        <StrategyView
          strategy={strategy}
          savedAmount={savedAmount}
          targetAmount={targetAmount}
        />
      ) : null}
    </div>
  )
}
